### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "0950470006",
  "amount": 10001
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "0950470006",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "8c3ae3adb2a54649aa81dd00dd3d7820",
  "accountNumber": "0950470006",
  "amount": 10000
}

### cancel balance2
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "8c3ae3adb2a54649aa81dd00dd3d7820",
  "accountNumber": "0950470006",
  "amount": 10000
}

### query transaction
GET http://localhost:8080/transaction/8c3ae3adb2a54649aa81dd00dd3d7820